### ISSUE TITLE
Error in files2SpectraObject

### ISSUE THREAD

**Issue by RosarioI** [bryanhanson/ChemoSpec#10]
Hello Bryan,
I am trying to use your package for analyzing some FTIR time course spectra. I exported the data from the proprietary format to .txt, converted them in .csv and formatted them as per the vignette. 
However, when I try to create the spectral file I got an error.

> files2SpectraObject(gr.crit = c("GEN1sp", "GEN2sp"), header = F, gr.cols = c("red3", "dodgerblue4"), out.file = "Test", debug = T)

The default behavior of this function has changed as of July 2016.  See ?files2SpectraObject

files2SpectraObject is checking the first file

files2SpectraObject will now import your files
Importing file:  GEN1sp0.csv 
Error in `[.data.frame`(temp, , 2) : undefined columns selected

Do you have any clue of what :undefined columns selected refers to?

Best wishes,
Rosario

**Comment by bryanhanson** [comment]
The solution is in `?files2SpectraObject`.  I made some changes there to allow more flexible importing and so now you have to specify your separator.  You may have to specify some other things too, but in your case most likely adding `sep = ","` to your call will fix it.  If not, see `?file2SpectraObject` or send to my regular e-mail several sample files you are trying to import.

**Comment by RosarioI** [comment]
Thank you very much. I will try your suggestions and I will let you know.


Best wishes,
Rosario

*Rosario Iacono*

5 King Street
SY23 2AY Aberystwyth
Ceredigion
Wales, UK
Ph. 07436974395
iaconorosario@gmail.com
LinkedIn <http://uk.linkedin.com/pub/rosario-iacono/23/b30/493/en>
Facebook <https://www.facebook.com/rosario.iacono>

2016-12-09 18:16 GMT+00:00 Bryan Hanson <notifications@github.com>:

**Comment by bryanhanson** [comment]
Rosario, did you get it working?

**Comment by sanloza** [comment]
Hey Bryan,

I was having the same problem as Rosario:
Error in [.data.frame(temp, , 2) : undefined columns selected

But with the extra argument sep = "," it fixes the argument.
I had a lot of trouble figuring out what the problem was and getting the fix, I read the 
?files2SpectraObject, tried to find an answer on Stack Overflow, and even tried to find the answer in here https://cran.r-project.org/web/packages/ChemoSpec/vignettes/ChemoSpec.pdf 

But with this response:
"""
The solution is in ?files2SpectraObject. I made some changes there to allow more flexible importing and so now you have to specify your separator. You may have to specify some other things too, but in your case most likely adding sep = "," to your call will fix it. If not, see ?file2SpectraObject or send to my regular e-mail several sample files you are trying to import.
"""
everything was clear, so I think you could add this to the ?files2SpectraObject to help with this error. 

Thank you for this great package!

Regards,
Santiago

**Comment by bryanhanson** [comment]
Thanks for your note Santiago.  All the information is in `?files2SpectraObject` but I will review it to see if I can make it clearer.  Bryan

**Comment by amorrison909** [comment]
Hi Bryan,

I'm new to using ChemoSpec and I was wondering if you would be able to help me with a similar issue that Rosario and Santiago had. I'm using `Files2SpectraObject` with the following code

```
spec <- files2SpectraObject(header = TRUE, sep = " ", dec = ".",
                            gr.crit = c("HDPE", "LDPE", "PP", "PS", "PET"), gr.cols = c("auto"), 
                            freq.unit = "nm", 
                            int.unit = "intensity",
                            descrip = "test import", 
                            fileExt = "\\.txt", debug = TRUE)
```

and I'm getting the following error:
```
Error message from R: undefined columns selected

There was a problem importing your files!

Are you importing csv or similar files?
Did you get a message such as 'undefined columns selected'?
You probably need to specify sep, header and dec values
Please read ?files2SpectraObject for details
```
I've added the correct sep, header, and dec values for my file formats, so I'm not sure what else I need to do. If you have any advice I would really appreciate it!

Thank you!
Alexandra

**Comment by bryanhanson** [comment]
Hi Alexandra.  First, can you please update to the newest versions?  There have been some significant changes under the hood.

```
update.packages("ChemoSpec") # latest version from CRAN
install.packages("devtools")
library("devtools")
install_github(repo = "bryanhanson/ChemoSpecUtils@devel") # CRAN version is slightly buggy
```
And try again.  Assuming you get the same result, I see you have `debug = TRUE`.  Does it stop on the first file?  If possible, can you send me ~5 files to play with as attachment to hanson@depauw.edu?

**Comment by RosarioI** [comment]
Thanks for keeping me in this conversation. I am about to use ChemoSpec
soon again and is good to know what is going on.

Best wishes

*Rosario Iacono*

5 King Street
SY23 2AY Aberystwyth
Ceredigion
Wales, UK
Ph. 07380466166
iaconorosario@gmail.com

**Comment by amorrison909** [comment]
Hi Bryan, thanks for your quick response! I updated as suggested and there was no change. It does stop importing at the first file, so I'll send some files your way.
Thanks!

**Comment by bryanhanson** [comment]
Hey Alexandra.  Your files have a header and use tab separation, so you need:

```
tst <- files2SpectraObject(
	gr.crit = c("HDPE", "LDPE", "PP"),
	freq.unit = "wavenumber",
	int.unit = "absorbance",
	descrip = "Alexandra's Plastics",
	fileExt = "\\.txt",
	debug = TRUE,
	sep = "\t", header = TRUE)
```
Notice that I left out the args `gr.cols` and `out.file`.  The current version has a bug in which these two arguments cause a problem.  Fortunately, you can leave them out as they have default values.  My hope is to get the bug fixed in the next day or so.

**Comment by amorrison909** [comment]
That fixes it, thank you for your help!
