### ISSUE TITLE
ChemoSpec: as.Spectra.data.frame function doesn't work

### ISSUE THREAD

**Issue by Leprechault** [bryanhanson/ChemoSpec#19]
as.Spectra.data.frame <- function(x, name, freq, intensity, group) {
	
	# Helper function
	isWholeNo <- function(x, tol = .Machine$double.eps^0.5) {abs(x - round(x)) < tol}	

	# A few checks
	if (length(units) != 2) stop("units should have length 2")
	
	# Determine dimensions
	no.pts <- length(unique(DF[,freq]))
	no.spec <- length(DF[,freq])/no.pts
	if (!isWholeNo(no.spec)) stop("no.spec was not an integer")
	
	# Now build the Spectra object
	Spectra <- vector("list", 9)
	Spectra[[1]] <- unique(DF[,freq]) # frequency
	Spectra[[2]] <- matrix(DF[,intensities], nrow = no.spec, byrow = TRUE)
	Spectra[[3]] <- as.character(unique(DF[,names])) # names
	Spectra[[4]] <- rep(NA_character_, no.spec) # groups
	Spectra[[5]] <- rep("black", no.spec) # colors
	Spectra[[6]] <- rep(1L, no.spec) # sym
	Spectra[[7]] <- rep("a", no.spec) # alt.sym
	Spectra[[8]] <- units # units
	Spectra[[9]] <- desc # desc

	# Update groups
	for (i in 1:length(gr.crit)) {
		which <- grep(gr.crit[i], Spectra[[3]])
		if (length(which) == 0) warning("There was no match for gr.crit value ", gr.crit[i], " among the sample names.")
		Spectra[[4]][which] <- gr.crit[i]
		}
	Spectra[[4]] <- as.factor(Spectra[[4]])

	# Clean up and verify
	
	class(Spectra) <- "Spectra"
	names(Spectra) <- c("freq", "data", "names", "groups", "colors", "sym", "alt.sym", "units", "desc")
	chkSpectra(Spectra)
	return(Spectra)
}

#First simulate some data
set.seed(123)
bands=20
data <- data.frame(matrix(runif(60*bands),ncol=bands))
colnames(data) <- paste0(1:bands)
#Structure
str(data)
#Convert to Spectra object using the function
test<-as.Spectra.data.frame(data)

Doesn't work, please help me? 
Thanks

**Comment by bryanhanson** [comment]
Your function wants a value for units, but it doesn't have them (I suppose you should add it as a single argument that combines your current freq and intensity arguments). Once you fix that, you still cannot do `test <- as.Spectra.data.frame(data)` because your function doesn't provide default values for the other arguments (name, freq, intensity, group).  If you combine freq and intensity into units, you'll still need to pass values for all the arguments.  Let me know if this helps.
