### ISSUE TITLE
plotting scores

### ISSUE THREAD

**Issue by abrahamemilia** [bryanhanson/ChemoSpec#22]
Hello, I´m new with ChemoSpec,
I tried to use plotScores function:
c_PCA <- c_pcaSpectra(dest,
choice = "noscale")
plotScores(dest, c_PCA, main = "PCA SCORES",
pcs = c(1,2),
ellipse = "rob",
tol = 0.01)
and the following error appeared:
Error in plot.window(...) : need finite 'xlim' values
How could I fix it? Thank you!

**Comment by bryanhanson** [comment]
Hi, thanks for using `ChemoSpec` and for your question.

First, please make sure you are using the latest versions of `ChemoSpec` and `ChemoSpecUtils` from CRAN.  If you recently installed you are fine, if not, please re-install from CRAN.

The error you see usually occurs because somewhere infinite or NaN values are present in whatever you are trying to plot.  Since you are plotting scores with ellipses, the problem must be with either the scores themselves (which I've never seen) or with the ellipse calculation and plotting (where sometimes there are issues but usually it exits more gracefully).  You can try setting `ellipse = 'none'` and see what happens, or `ellipse = 'rob'`.

Beyond that, perhaps you could share your original data ("dest.RData") -- you can send it to me at hanson@depauw.edu and then I could troubleshoot.

**Comment by abrahamemilia** [comment]
Hi, thanks to you for your quick answer! 
When I set ellipse='none' it worked, but not with ellipse='rob'. I didn't figure the problem could be the ellipse.
I'm running some preliminary analysis, so if the problem persists when the dataset is complete I'm will send you the full dataset.
Again, thank you for your response!
Emilia.

**Comment by bryanhanson** [comment]
Thanks Emilia, please keep me posted on further problems. I'll leave this open for a while.

I would be interested to know if `ellipse = "cls"` works when you have a chance.  I will guess that it will work.

The robust ellipse calculation has a means of identifying outliers, and in your case it may have chosen too many points as outliers and then run into trouble.  I'm not sure.  It's someone else's code I am using, and I've almost never had a problem with it.  On the other hand, I currently am working with a data set that looks quite typical but the ellipse calculation fails, with a claim of singularity.  That's not the error you see, but maybe I need to investigate if something has changed under the hood.

**Comment by bryanhanson** [comment]
Closing for now, we can always re-open.
