### ISSUE TITLE
problem with the removeFreq function in chemospec 5.3.2

### ISSUE THREAD

**Issue by YEstevez** [bryanhanson/ChemoSpec#29]
Hello.
I process NMR spectra in Rstudio with the Chemospec package.
The data used are csv separated by a tab.
The problem is that after 10ppm, the data is no longer continuous and I can't remove the higher values with the remoFreq function.
The frequency scale runs from -2.01194 to 11.9976 no intensity unit provided
There are 57268 frequency values.
The frequency resolution is 0.000244 no intensity unit provided/point.

This data set is not continuous along the frequency axis.
	Here are the data chunks:

    beg.freq end.freq     size beg.indx end.indx
1   -2.01194  10.0001 12.01204        1    49103
2   10.00040  10.0006  0.00020    49104    49105
3   10.00090  10.0013  0.00040    49106    49108
4   10.00160  10.0018  0.00020    49109    49110
5   10.00210  10.0023  0.00020    49111    49112
6   10.00260  10.0028  0.00020    49113    49114
Do you have an idea of the problem?
thank you in advance

**Comment by bryanhanson** [comment]
Hi @YEstevez thanks for your question.  So it sounds like you can read the data into a `Spectra` object, but when you try to use the data you run into various functions complaining about gaps?  Is that right?

This would be easiest to troubleshoot if you can share either the `Spectra` object or a few of the csv files, along the script you used to import the csv files.  You can send these to hanson@depauw.edu as attachments.  I will not share the data with anyone.

There is a `tolerance` value used internally for the gap check and there is a way to access it but I need to see the data to see what's going on.  The problem is probably an artifact of the export process because the point spacing on digital NMR generally is constant.

**Comment by YEstevez** [comment]
Thank you Bryan for your prompt response. I am sending you some csv files and the script 
Yannick

**Comment by bryanhanson** [comment]
Very good, I'll look for the files.  I just moved and only have a primitive internet connection but I'll be as quick as I can.

**Comment by bryanhanson** [comment]
Problem fixed; `tol` needed to be set and documentation made clearer about this.

**Comment by YEstevez** [comment]
Thanks you Brian

I test tomorrow

Best

Yannick
________________________________
De : Bryan Hanson [notifications@github.com]
Envoyé : lundi 1 mars 2021 18:20
À : bryanhanson/ChemoSpec
Cc : Yannick Estevez; Mention
Objet : Re: [bryanhanson/ChemoSpec] problem with the removeFreq function in chemospec 5.3.2 (#29)


Problem fixed; tol needed to be set and documentation made clearer about this.
