### ISSUE TITLE
matrix2SpectraObject 'Error' Bringing in CSV

### ISSUE THREAD

**Issue by skazmer** [bryanhanson/ChemoSpec#32]
Hello, 

I have lost much time trying to get the chemospec package to read my simple CSV file, which follows the requested profile. 

Initially the error was as follows:
Error in matrix2SpectraObject(VIT_ctrl_A_Covid_B) : 
  You need to specify an input file

However, despite much effort specifying: gr.crit, gr.cols, in.file, etc...
I cannot get my file read into chemospec. Additionally, I seem to have all the tools and util., required. 
Please help me through step 1 so I may begin working on the data.

Thank you!
S

**Comment by skazmer** [comment]
My File 
[VIT ctrl A Covid B.pdf](https://github.com/bryanhanson/ChemoSpec/files/6558854/VIT.ctrl.A.Covid.B.pdf)

**Comment by skazmer** [comment]
[VIT ctrl A Test B.pdf](https://github.com/bryanhanson/ChemoSpec/files/6558858/VIT.ctrl.A.Test.B.pdf)
My File

**Comment by bryanhanson** [comment]
Can you send your input file as an attachment in csv format, along with the `R` script you are using to read it in?

If you can't share the data, I have three suggestions that might be part of the problem:

1. In your input file you have as the very first entry `X [1/cm]` `R` can be picky about slashes in column names because eventually it make take the slash as meaning division.
2. The spaces in the sample names may also be causing some problems.  I suggest replacing the spaces in the name with underscores.
3. Be sure in your call to `matrix2SpectraObject` that you give appropriate values for `sep` and `dec`.  See the help file `?matrix2SpectraObject`.

Also, it would be very helpful to have the exact error message you are getting (but even better if you can share the files in readible format).

**Comment by skazmer** [comment]
I am unable to attach a file in CSV format. I get an error stating that the filetype is not accepted. 
Thank you for your help.

**Comment by bryanhanson** [comment]
You can rename it to *.txt and I think Github will allow you to attach or send as attachments to ***@***.***

**Comment by bryanhanson** [comment]
Closing, problems were fixed outside of Github.
