### ISSUE TITLE
Possible bug in reading DX files

### ISSUE THREAD

**Issue by miguelfrocha** [bryanhanson/ChemoSpec#7]
We are using some of the functions from ChemoSpec to load DX files in our package specmine.

Recently, when I updated the ChemoSpec package we suddenly became unable to read DX files, always returning the error:

"Problem understanding data block"

I was looking at the code and this seems to be related to some changes you added in version 4.3.30.
More specifically the following line of the function readJDX:
if (!length(spcstart) == 1L & length(spcend) == 1L) stop("Problem with delimiting data block")

seems incorrect. Maybe a ! is missing before length(spcend) ?
With this correction my files seem to load properly as before.

Miguel Rocha
mrocha@di.uminho.pt

**Comment by bryanhanson** [comment]
Thanks Miguel for the report.  I will look into that line of code you mention.  However, I am in the process of completing a new package that just reads JCAMP-DX files (and returns x, y coordinates).  In the next month or two it will be made public and then ChemoSpec will use it.  The current ChemoSpec version only handles a small set of the JCAMP format and the new package will handle a lot more.  So I guess 1) if you made it work for you now, great, and 2) I'll let you know when the new package becomes available, and 3) I'll check the line you note because I think the same one is in the new package.  Let me just say that JCAMP-DX format gives me bad dreams!

**Comment by miguelfrocha** [comment]
Ok, we will release a version of specmine with our own version (basicaly the same with that line fixed) for now. When the new package is available we will give it a try. Thanks.

**Comment by bryanhanson** [comment]
Sounds good.

**Comment by bryanhanson** [comment]
Miguel, I'm going to close this old issue.  I also just put a new version of `readJDX` on CRAN, it's 0.3.250 should be there in a few hours at most (on the Austrian server).
